package:
  name: pywr
  version: "0.1"

source:
  git_rev: winpy3k
  git_url: https://github.com/pywr/pywr.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - cython
    - glpk
  run:
    - python
    - numpy x.x
    - pandas
    - networkx
    - glpk

test:
  imports:
    - pywr

about:
  home: https://github.com/pywr/pywr
  license: GPL
  license_file: LICENSE.txt
  summary: Water resource model written in Python
