package:
  name: lru-dict
  version: "1.1.3"

source:
  fn: lru-dict-1.1.3.tar.gz
  url: https://pypi.python.org/packages/source/l/lru-dict/lru-dict-1.1.3.tar.gz
  md5: ff61d0109e3e9b75376fa44422f25e89

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - lru

about:
  home: https://github.com/amitdev/lru-dict
  license: MIT License
  summary: 'An Dict like LRU container.'
